<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cameramaster extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cameramaster_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of cameramaster
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('cameramaster/index?');
        $config['total_rows'] = $this->Cameramaster_model->get_all_cameramaster_count();
        $this->pagination->initialize($config);

        $data['cameramaster'] = $this->Cameramaster_model->get_all_cameramaster($params);
        
        $data['_view'] = 'cameramaster/index';
        $this->load->view('layouts/main',$data);
    }
	
	/*
     * Listing of cameramaster
     */
    function status()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('cameramaster/index?');
        $config['total_rows'] = $this->Cameramaster_model->get_all_cameramaster_count();
        $this->pagination->initialize($config);

        $data['cameramaster'] = $this->Cameramaster_model->get_all_cameramaster($params);
        
        $data['_view'] = 'cameramaster/status';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cameramaster
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'camera_name' => $this->input->post('camera_name'),
				'camera_startTime' => $this->input->post('camera_startTime'),
				'camera_stopTime' => $this->input->post('camera_stopTime'),
				'camera_inc' => $this->input->post('camera_inc'),
            );
            
            $cameramaster_id = $this->Cameramaster_model->add_cameramaster($params);
            redirect('cameramaster/index');
        }
        else
        {            
            $data['_view'] = 'cameramaster/add';
            $this->load->view('layouts/main',$data);
        }
    }  
	
	/*
     * Editing a cameramaster
     */
    function updatecamerastatus($camera_id)
    {   
        // check if the cameramaster exists before trying to edit it
        $data['cameramaster'] = $this->Cameramaster_model->get_cameramaster($camera_id);
        
        if(isset($data['cameramaster']['camera_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'camera_name' => $this->input->post('camera_name'),
					'camera_startTime' => $this->input->post('camera_startTime'),
					'camera_stopTime' => $this->input->post('camera_stopTime'),
					'latestimg' => $this->input->post('latestimg'),
					'camera_inc' => $this->input->post('camera_inc'),
                );

                $this->Cameramaster_model->update_cameramaster($camera_id,$params);            
                return 'ok 200';
            }
            else
            {
                return 'not ok no post data';
            }
        }
        else
             return 'not ok no cameraid data';
    } 
	
    /*
     * Editing a cameramaster
     */
    function edit($camera_id)
    {   
        // check if the cameramaster exists before trying to edit it
        $data['cameramaster'] = $this->Cameramaster_model->get_cameramaster($camera_id);
        
        if(isset($data['cameramaster']['camera_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'camera_name' => $this->input->post('camera_name'),
					'camera_startTime' => $this->input->post('camera_startTime'),
					'camera_stopTime' => $this->input->post('camera_stopTime'),
					'camera_inc' => $this->input->post('camera_inc'),
                );

                $this->Cameramaster_model->update_cameramaster($camera_id,$params);            
                redirect('cameramaster/index');
            }
            else
            {
                $data['_view'] = 'cameramaster/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cameramaster you are trying to edit does not exist.');
    } 

    /*
     * Deleting cameramaster
     */
    function remove($camera_id)
    {
        $cameramaster = $this->Cameramaster_model->get_cameramaster($camera_id);

        // check if the cameramaster exists before trying to delete it
        if(isset($cameramaster['camera_id']))
        {
            $this->Cameramaster_model->delete_cameramaster($camera_id);
            redirect('cameramaster/index');
        }
        else
            show_error('The cameramaster you are trying to delete does not exist.');
    }
    
}
