<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Location_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of location
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('location/index?');
        $config['total_rows'] = $this->Location_model->get_all_location_count();
        $this->pagination->initialize($config);

        $data['location'] = $this->Location_model->get_all_location($params);
        
        $data['_view'] = 'location/index';
         
    }
}
