<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Intrusiondetail_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    }

    function index()
    {
		$data['_view'] = 'dashboard';
		$params = array('incidentstatus' => 'O');
		$param = array('incidentstatus' => 'O');

		$data['int'] = $this->Intrusiondetail_model->get_all_intrusiondetails('',$params);
		#$param = array('incidentstatus' => 'O', 'intrusion_time' => 'DATE_SUB(curdate(), INTERVAL 7 DAY)');

		unset($_SESSION['dsstrdate']);
		unset($_SESSION['dsenddate']);
		unset($_SESSION['dslocation']);
		unset($_SESSION['dsstatus']);

		if(isset($_POST['strdate']) && !empty($_POST['strdate'])){
			$_SESSION['dsstrdate'] = $_POST['strdate'];
			$param['DATE(intrusiondetails.intrusion_time) >='] = $_POST['strdate'];
		}
		if(isset($_POST['enddate']) && !empty($_POST['enddate'])){
			$_SESSION['dsenddate'] = $_POST['enddate'];
			$param['DATE(intrusiondetails.intrusion_time) <='] = $_POST['enddate'];
		}
		if(isset($_POST['location']) && !empty($_POST['location'])){
			$_SESSION['dslocation'] = $_POST['location'];
			$param['intrusiondetails.locationid'] = $_POST['location'];
		}			
		if(isset($_POST['status']) && !empty($_POST['status'])){
			$_SESSION['dsstatus'] = $_POST['status'];
			$param['intrusiondetails.incidentstatus'] = $_POST['status'];
		}
		$this->load->model('Location_model');
		$data['locationsdata'] = $this->Location_model->get_all_location();

		$date = strtotime("-7 day");
		$d = date('Y-m-d', $date);

		$paramintweek = array('incidentstatus' => 'O','intrusion_time >=' => $d);
		// $param['incidentstatus'] = 'O';
		// $param['intrusion_time >='] = $d;
		$data['intweek'] = $this->Intrusiondetail_model->get_all_intrusiondetails('',$paramintweek);
		
		
		$date = strtotime("-3 month");
		$d = date('Y-m-d', $date);

		// $param = array('incidentstatus' => 'O','intrusion_time >=' => $d);
		// $param['incidentstatus'] = 'O';
		// $param['intrusion_time >='] = $d;
		$data['in3month'] = $this->Intrusiondetail_model->get_all_intrusiondetails('',$param);
		
		
		$a = array();
		$b = array();
		$c = array();
		#echo count($data['in3month']);
		foreach ($data['in3month'] as $intrutiondata) {
			//code to be executed;
			#$data['locationname'][] = 
			array_push($a,$intrutiondata['locationname']);
			array_push($c,date("Y-m-d",strtotime($intrutiondata['intrusion_time'])));

			$tarray = explode(",",$intrutiondata['intrusiontype']);
			foreach ($tarray  as $tarrayval) {
				array_push($b,$tarrayval);
			}
			#print_r(explode(",",$intrutiondata['intrusiontype']));
		}
		
		#echo "<pre>";
		$newarray = array_values($a);
		
		$newarray = array_count_values($newarray);
		$newbarray = array_count_values($b);

		$newcarray = array_values($c);
		$newcarray = array_count_values($newcarray);
		
		arsort($newarray);
		arsort($newbarray);
		arsort($newbarray);
		
		#echo "<pre>"; print_r($newcarray);exit;
		$data['locations'] = $newarray;
		$data['intrutype'] = $newbarray;
		$data['datewiseincident'] = $newcarray;
		#var_dump($newarray);
        
		// print_r($data['locations']);exit;
		 
		$this->load->view('layouts/main',$data);
		
    }
}
