<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Device_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of devices
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('device/index?');
        $config['total_rows'] = $this->Device_model->get_all_devices_count();
        $this->pagination->initialize($config);

        $data['devices'] = $this->Device_model->get_all_devices($params);
        
        $data['_view'] = 'device/index';
        $this->load->view('layouts/main',$data);
    }
	
	 /*
     * Listing of devices
     */
    function status()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('device/status?');
        $config['total_rows'] = $this->Device_model->get_all_devices_count();
        $this->pagination->initialize($config);

        $data['devices'] = $this->Device_model->get_all_devices($params);
        $data['_view'] = 'device/status';
        $this->load->view('layouts/main',$data);
    }
	
	 /*
     * Editing a device
     */
    function statusupdate($deviceid)
    {   
        // check if the device exists before trying to edit it
        $data['device'] = $this->Device_model->get_device($deviceid);
        
        if(isset($data['device']['deviceid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'locationid' => $this->input->post('locationid'),
					'raspieid' => $this->input->post('raspieid'),
					'raspiename' => $this->input->post('raspiename'),
					'camera1id' => $this->input->post('camera1id'),
					'camera1name' => $this->input->post('camera1name'),
					'camera2id' => $this->input->post('camera2id'),
					'camera2name' => $this->input->post('camera2name'),
					'camera3id' => $this->input->post('camera3id'),
					'camera3name' => $this->input->post('camera3name'),
					'camera4id' => $this->input->post('camera4id'),
					'camera4name' => $this->input->post('camera4name'),
					'camera5id' => $this->input->post('camera5id'),
					'camera5name' => $this->input->post('camera5name'),
					'devicestatus' => $this->input->post('devicestatus'),
                );

                $this->Device_model->update_device($deviceid,$params);            
                redirect('device/index');
            }
            else
            {
				$this->load->model('Location_model');
				$data['all_location'] = $this->Location_model->get_all_location();

                $data['_view'] = 'device/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The device you are trying to edit does not exist.');
	}
	
	
    /*
     * Adding a new device
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'locationid' => $this->input->post('locationid'),
				'raspieid' => $this->input->post('raspieid'),
				'raspiename' => $this->input->post('raspiename'),
				'camera1id' => $this->input->post('camera1id'),
				'camera1name' => $this->input->post('camera1name'),
				'camera2id' => $this->input->post('camera2id'),
				'camera2name' => $this->input->post('camera2name'),
				'camera3id' => $this->input->post('camera3id'),
				'camera3name' => $this->input->post('camera3name'),
				'camera4id' => $this->input->post('camera4id'),
				'camera4name' => $this->input->post('camera4name'),
				'camera5id' => $this->input->post('camera5id'),
				'camera5name' => $this->input->post('camera5name'),
				'devicestatus' => $this->input->post('devicestatus'),
            );
            
            $device_id = $this->Device_model->add_device($params);
            redirect('device/index');
        }
        else
        {
			$this->load->model('Location_model');
			$data['all_location'] = $this->Location_model->get_all_location();
            
            $data['_view'] = 'device/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a device
     */
    function edit($deviceid)
    {   
        // check if the device exists before trying to edit it
        $data['device'] = $this->Device_model->get_device($deviceid);
        
        if(isset($data['device']['deviceid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'locationid' => $this->input->post('locationid'),
					'raspieid' => $this->input->post('raspieid'),
					'raspiename' => $this->input->post('raspiename'),
					'camera1id' => $this->input->post('camera1id'),
					'camera1name' => $this->input->post('camera1name'),
					'camera2id' => $this->input->post('camera2id'),
					'camera2name' => $this->input->post('camera2name'),
					'camera3id' => $this->input->post('camera3id'),
					'camera3name' => $this->input->post('camera3name'),
					'camera4id' => $this->input->post('camera4id'),
					'camera4name' => $this->input->post('camera4name'),
					'camera5id' => $this->input->post('camera5id'),
					'camera5name' => $this->input->post('camera5name'),
					'devicestatus' => $this->input->post('devicestatus'),
                );

                $this->Device_model->update_device($deviceid,$params);            
                redirect('device/index');
            }
            else
            {
				$this->load->model('Location_model');
				$data['all_location'] = $this->Location_model->get_all_location();

                $data['_view'] = 'device/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The device you are trying to edit does not exist.');
    } 

    /*
     * Deleting device
     */
    function remove($deviceid)
    {
        $device = $this->Device_model->get_device($deviceid);

        // check if the device exists before trying to delete it
        if(isset($device['deviceid']))
        {
            $this->Device_model->delete_device($deviceid);
            redirect('device/index');
        }
        else
            show_error('The device you are trying to delete does not exist.');
    }
    
}
