<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Location_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of location
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('location/index?');
        $config['total_rows'] = $this->Location_model->get_all_location_count();
        $this->pagination->initialize($config);

        $data['location'] = $this->Location_model->get_all_location($params);
        
        $data['_view'] = 'location/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new location
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'locationname' => $this->input->post('locationname'),
				'locationplace' => $this->input->post('locationplace'),
				'address' => $this->input->post('address'),
            );
            
            $location_id = $this->Location_model->add_location($params);
            redirect('location/index');
        }
        else
        {            
            $data['_view'] = 'location/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a location
     */
    function edit($locationid)
    {   
        // check if the location exists before trying to edit it
        $data['location'] = $this->Location_model->get_location($locationid);
        
        if(isset($data['location']['locationid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'locationname' => $this->input->post('locationname'),
					'locationplace' => $this->input->post('locationplace'),
					'address' => $this->input->post('address'),
                );

                $this->Location_model->update_location($locationid,$params);            
                redirect('location/index');
            }
            else
            {
                $data['_view'] = 'location/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The location you are trying to edit does not exist.');
    } 

    /*
     * Deleting location
     */
    function remove($locationid)
    {
        $location = $this->Location_model->get_location($locationid);

        // check if the location exists before trying to delete it
        if(isset($location['locationid']))
        {
            $this->Location_model->delete_location($locationid);
            redirect('location/index');
        }
        else
            show_error('The location you are trying to delete does not exist.');
    }
    
}
