<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Memberdetail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Memberdetail_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of memberdetails
     */
    function index()
    {
        $data['memberdetails'] = $this->Memberdetail_model->get_all_memberdetails();
        
        $data['_view'] = 'memberdetail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new memberdetail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'member_name' => $this->input->post('member_name'),
				'school_id' => $this->input->post('school_id'),
				'member_address' => $this->input->post('member_address'),
				'member_email' => $this->input->post('member_email'),
				'member_number' => $this->input->post('member_number'),
				'createdBy' => $this->input->post('createdBy'),
				'createdOn' => $this->input->post('createdOn'),
				'modifiedBy' => $this->input->post('modifiedBy'),
				'modifiedOn' => $this->input->post('modifiedOn'),
            );
            
            $memberdetail_id = $this->Memberdetail_model->add_memberdetail($params);
            redirect('memberdetail/index');
        }
        else
        {            
            $data['_view'] = 'memberdetail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a memberdetail
     */
    function edit($member_id)
    {   
        // check if the memberdetail exists before trying to edit it
        $data['memberdetail'] = $this->Memberdetail_model->get_memberdetail($member_id);
        
        if(isset($data['memberdetail']['member_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'member_name' => $this->input->post('member_name'),
					'school_id' => $this->input->post('school_id'),
					'member_address' => $this->input->post('member_address'),
					'member_email' => $this->input->post('member_email'),
					'member_number' => $this->input->post('member_number'),
					'createdBy' => $this->input->post('createdBy'),
					'createdOn' => $this->input->post('createdOn'),
					'modifiedBy' => $this->input->post('modifiedBy'),
					'modifiedOn' => $this->input->post('modifiedOn'),
                );

                $this->Memberdetail_model->update_memberdetail($member_id,$params);            
                redirect('memberdetail/index');
            }
            else
            {
                $data['_view'] = 'memberdetail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The memberdetail you are trying to edit does not exist.');
    } 

    /*
     * Deleting memberdetail
     */
    function remove($member_id)
    {
        $memberdetail = $this->Memberdetail_model->get_memberdetail($member_id);

        // check if the memberdetail exists before trying to delete it
        if(isset($memberdetail['member_id']))
        {
            $this->Memberdetail_model->delete_memberdetail($member_id);
            redirect('memberdetail/index');
        }
        else
            show_error('The memberdetail you are trying to delete does not exist.');
    }
    
}
