<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Schoolmaster extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Schoolmaster_model');
		if($this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of schoolmaster
     */
    function index()
    {
        $data['schoolmaster'] = $this->Schoolmaster_model->get_all_schoolmaster();
        
        $data['_view'] = 'schoolmaster/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new schoolmaster
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'school_name' => $this->input->post('school_name'),
				'school_address' => $this->input->post('school_address'),
				'school_email' => $this->input->post('school_email'),
				'school_number' => $this->input->post('school_number'),
				'school_city' => $this->input->post('school_city'),
				'school_pincode' => $this->input->post('school_pincode'),
				'createdBy' => $this->input->post('createdBy'),
				'createdOn' => $this->input->post('createdOn'),
				'modifiedBy' => $this->input->post('modifiedBy'),
				'modifiedOn' => $this->input->post('modifiedOn'),
				'status' => $this->input->post('status'),
				'school_inc' => $this->input->post('school_inc'),
				'logoimagepath' => $this->input->post('logoimagepath'),
            );
            
            $schoolmaster_id = $this->Schoolmaster_model->add_schoolmaster($params);
            redirect('schoolmaster/index');
        }
        else
        {            
            $data['_view'] = 'schoolmaster/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a schoolmaster
     */
    function edit($school_id)
    {   
        // check if the schoolmaster exists before trying to edit it
        $data['schoolmaster'] = $this->Schoolmaster_model->get_schoolmaster($school_id);
        
        if(isset($data['schoolmaster']['school_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'school_name' => $this->input->post('school_name'),
					'school_address' => $this->input->post('school_address'),
					'school_email' => $this->input->post('school_email'),
					'school_number' => $this->input->post('school_number'),
					'school_city' => $this->input->post('school_city'),
					'school_pincode' => $this->input->post('school_pincode'),
					'createdBy' => $this->input->post('createdBy'),
					'createdOn' => $this->input->post('createdOn'),
					'modifiedBy' => $this->input->post('modifiedBy'),
					'modifiedOn' => $this->input->post('modifiedOn'),
					'status' => $this->input->post('status'),
					'school_inc' => $this->input->post('school_inc'),
					'logoimagepath' => $this->input->post('logoimagepath'),
                );

                $this->Schoolmaster_model->update_schoolmaster($school_id,$params);            
                redirect('schoolmaster/index');
            }
            else
            {
                $data['_view'] = 'schoolmaster/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The schoolmaster you are trying to edit does not exist.');
    } 

    /*
     * Deleting schoolmaster
     */
    function remove($school_id)
    {
        $schoolmaster = $this->Schoolmaster_model->get_schoolmaster($school_id);

        // check if the schoolmaster exists before trying to delete it
        if(isset($schoolmaster['school_id']))
        {
            $this->Schoolmaster_model->delete_schoolmaster($school_id);
            redirect('schoolmaster/index');
        }
        else
            show_error('The schoolmaster you are trying to delete does not exist.');
    }
    
}
