<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usermaster extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usermaster_model');
 		$this->load->library('javascript');
		$this->load->library('form_validation');
		$this->load->library('email');
		$this->load->library('session');

		if($this->router->fetch_method() != 'login' && $this->session->userdata('logged_in') !== TRUE){
			redirect('/usermaster/login');
		}
    } 

    /*
     * Listing of usermaster
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('usermaster/index?');
        $config['total_rows'] = $this->Usermaster_model->get_all_usermaster_count();
        $this->pagination->initialize($config);

        $data['usermaster'] = $this->Usermaster_model->get_all_usermaster($params);
        
        $data['_view'] = 'usermaster/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new usermaster
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'srofficerid' => $this->input->post('srofficerid'),
				'username' => $this->input->post('username'),
				'userpwd' => $this->input->post('userpwd'),
				'useremail' => $this->input->post('useremail'),
				'usernumber' => $this->input->post('usernumber'),
				'userrole' => $this->input->post('userrole'),
				'school_id' => $this->input->post('school_id'),
				'location' => $this->input->post('location'),
				'team' => $this->input->post('team'),
				'phoneno' => $this->input->post('phoneno'),
				'name' => $this->input->post('name'),
            );
            
            $usermaster_id = $this->Usermaster_model->add_usermaster($params);
            redirect('usermaster/index');
        }
        else
        {			$data['all_usermaster'] = $this->Usermaster_model->get_all_usermaster();
            
            $data['_view'] = 'usermaster/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a usermaster
     */
    function edit($userid)
    {   
        // check if the usermaster exists before trying to edit it
        $data['usermaster'] = $this->Usermaster_model->get_usermaster($userid);
        
        if(isset($data['usermaster']['userid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'srofficerid' => $this->input->post('srofficerid'),
					'username' => $this->input->post('username'),
					'userpwd' => $this->input->post('userpwd'),
					'useremail' => $this->input->post('useremail'),
					'usernumber' => $this->input->post('usernumber'),
					'userrole' => $this->input->post('userrole'),
					'school_id' => $this->input->post('school_id'),
					'location' => $this->input->post('location'),
					'team' => $this->input->post('team'),
					'phoneno' => $this->input->post('phoneno'),
					'name' => $this->input->post('name'),
                );

                $this->Usermaster_model->update_usermaster($userid,$params);            
                redirect('usermaster/index');
            }
            else
            {	
				$data['all_usermaster'] = $this->Usermaster_model->get_all_usermaster();
                $data['_view'] = 'usermaster/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usermaster you are trying to edit does not exist.');
    } 

    /*
     * Deleting usermaster
     */
    function remove($userid)
    {
        $usermaster = $this->Usermaster_model->get_usermaster($userid);

        // check if the usermaster exists before trying to delete it
        if(isset($usermaster['userid']))
        {
            $this->Usermaster_model->delete_usermaster($userid);
            redirect('usermaster/index');
        }
        else
            show_error('The usermaster you are trying to delete does not exist.');
    }
	 /*
     * Deleting usermaster
     */
	public function login123()
	{
		
		if($this->input->post('login'))
		{
			$e=$this->input->post('email');
			$p=$this->input->post('pass');
	
			$que=$this->db->query("select * from usermaster where username='".$e."' and password='$p'");
			$row = $que->num_rows();
			if($row){
				redirect('User/dashboard');
			}else
			{
				$data['error']="<h3 style='color:red'>Invalid login details</h3>";
			}	
		}		
		$this->load->view('layouts/login',@$data);		
	}
	
	
	public function login() {
		
        $this->form_validation->set_rules('username', 'Username', 'required');
        $this->form_validation->set_rules('password', 'Password', 'required');
 
        if ($this->form_validation->run() == FALSE) {
            $this->load->view('layouts/login');
        } else {
 
            $username = $this->input->post('username');
            $password = $this->input->post('password'); 
			 
			$que=$this->db->query("select * from usermaster where username='".$username."' and userpwd='".$password."'");
			$row = $que->num_rows();
			
			if(!$row){
             
                $this->session->set_flashdata('login_error', "Please check your username or password and try again.", 300);
                redirect(uri_string());
            } 
			$user = $this->db->get_where('usermaster',['username' => $username])->row();
            /*if(!password_verify($password,$user->userpwd)) {
                $this->session->set_flashdata('login_error', 'Please check your username or password and try again.', 300);
                redirect(uri_string());
            }*/
 
             $data = array(
                    'user_name' => $user->name,
                    'email' => $user->useremail,
					'role'     => $user->userrole,
					'logged_in' => TRUE
                    ); 
			 
            $this->session->set_userdata($data);
 
            redirect('/'); // redirect to home
            echo 'Login success!'; exit; 
        }        
    }
 
    public function logout(){
        $this->session->sess_destroy();
        redirect('usermaster/login');
    }
}
