<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cameramaster_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cameramaster by camera_id
     */
    function get_cameramaster($camera_id)
    {
        return $this->db->get_where('cameramaster',array('camera_id'=>$camera_id))->row_array();
    }
    
    /*
     * Get all cameramaster count
     */
    function get_all_cameramaster_count()
    {
        $this->db->from('cameramaster');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all cameramaster
     */
    function get_all_cameramaster($params = array())
    {
        $this->db->order_by('camera_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('cameramaster')->result_array();
    }
        
    /*
     * function to add new cameramaster
     */
    function add_cameramaster($params)
    {
        $this->db->insert('cameramaster',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cameramaster
     */
    function update_cameramaster($camera_id,$params)
    {
        $this->db->where('camera_id',$camera_id);
        return $this->db->update('cameramaster',$params);
    }
    
    /*
     * function to delete cameramaster
     */
    function delete_cameramaster($camera_id)
    {
        return $this->db->delete('cameramaster',array('camera_id'=>$camera_id));
    }
}
