<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get device by deviceid
     */
    function get_device($deviceid)
    {
        return $this->db->get_where('devices',array('deviceid'=>$deviceid))->row_array();
    }
    
    /*
     * Get all devices count
     */
    function get_all_devices_count()
    {
        $this->db->from('devices'); 
        return $this->db->count_all_results();
    }
        
    /*
     * Get all devices
     */
    function get_all_devices($params = array())
    {
        $this->db->order_by('deviceid', 'desc');
		$this->db->join('location', 'devices.locationid = location.locationid');

        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('devices')->result_array();
    }
        
    /*
     * function to add new device
     */
    function add_device($params)
    {
        $this->db->insert('devices',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update device
     */
    function update_device($deviceid,$params)
    {
        $this->db->where('deviceid',$deviceid);
        return $this->db->update('devices',$params);
    }
    
    /*
     * function to delete device
     */
    function delete_device($deviceid)
    {
        return $this->db->delete('devices',array('deviceid'=>$deviceid));
    }
}
