<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Intrusiondetail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
		/* Load Models - Model_1 */
		$this->load->model('Location_model');

    }
    
	public function get_all_location(){
  
    /* Access Two model methods and assing response to Array */
    $response[] = $this->Location_model->get_all_location();
    
    return $response;
  }

    /*
     * Get intrusiondetail by intrusion_id
     */
    function get_intrusiondetail($intrusion_id)
    {
		$this->db->select('*');    
		#Join on location table 
		$this->db->join('location', 'intrusiondetails.locationid = location.locationid','LEFT');
		#$this->db->join('table3', 'table1.id = table3.id'); how to join 3 tables 
		$this->db->order_by('intrusiondetails.intrusion_id', 'desc');
		$this->db->limit(100);
		#$query = $this->db->get();
		#return $query->result();
		return $this->db->get_where('intrusiondetails',array('intrusion_id'=>$intrusion_id))->row_array();
    }
        
    /*
     * Get all intrusiondetails
     */
    function get_all_intrusiondetails($params = array(),$where = array())
    {		
		$this->db->select('*');   
		$this->db->join('location', 'intrusiondetails.locationid = location.locationid','LEFT');
		
        $this->db->order_by('intrusiondetails.intrusion_id', 'desc');
		
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		
		if(isset($where) && !empty($where)){
			return $this->db->get_where('intrusiondetails',$where)->result_array();	
		}else{
			return $this->db->get('intrusiondetails')->result_array();
		}
    }
        
    /*
     * function to add new intrusiondetail
     */
    function add_intrusiondetail($params)
    {
        $this->db->insert('intrusiondetails',$params);
        return $this->db->insert_id();
    }
    
	 /*
     * Get all intrusiondetails  count
     */
    function get_all_intrusiondetails_count()
    {
        $this->db->from('intrusiondetails');
        return $this->db->count_all_results();
    }
        
		
    /*
     * function to update intrusiondetail
     */
    function update_intrusiondetail($intrusion_id,$params)
    {
        $this->db->where('intrusion_id',$intrusion_id);
        return $this->db->update('intrusiondetails',$params);
    }
    
    /*
     * function to delete intrusiondetail
     */
    function delete_intrusiondetail($intrusion_id)
    {
        return $this->db->delete('intrusiondetails',array('intrusion_id'=>$intrusion_id));
    }
}
