<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get location by locationid
     */
    function get_location($locationid)
    {
        return $this->db->get_where('location',array('locationid'=>$locationid))->row_array();
    }
    
    /*
     * Get all location count
     */
    function get_all_location_count()
    {
        $this->db->from('location');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all location
     */
    function get_all_location($params = array())
    {
        $this->db->order_by('locationid', 'desc');
		$this->db->where('locationstatus','O');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('location')->result_array();
    }
        
    /*
     * function to add new location
     */
    function add_location($params)
    {
        $this->db->insert('location',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update location
     */
    function update_location($locationid,$params)
    {
        $this->db->where('locationid',$locationid);
        return $this->db->update('location',$params);
    }
    
    /*
     * function to delete location
     */
    function delete_location($locationid)
    {
        return $this->db->delete('location',array('locationid'=>$locationid));
    }
}
