<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Memberdetail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get memberdetail by member_id
     */
    function get_memberdetail($member_id)
    {
        return $this->db->get_where('memberdetails',array('member_id'=>$member_id))->row_array();
    }
        
    /*
     * Get all memberdetails
     */
    function get_all_memberdetails()
    {
        $this->db->order_by('member_id', 'desc');
        return $this->db->get('memberdetails')->result_array();
    }
        
    /*
     * function to add new memberdetail
     */
    function add_memberdetail($params)
    {
        $this->db->insert('memberdetails',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update memberdetail
     */
    function update_memberdetail($member_id,$params)
    {
        $this->db->where('member_id',$member_id);
        return $this->db->update('memberdetails',$params);
    }
    
    /*
     * function to delete memberdetail
     */
    function delete_memberdetail($member_id)
    {
        return $this->db->delete('memberdetails',array('member_id'=>$member_id));
    }
}
