<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Schoolmaster_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get schoolmaster by school_id
     */
    function get_schoolmaster($school_id)
    {
        return $this->db->get_where('schoolmaster',array('school_id'=>$school_id))->row_array();
    }
        
    /*
     * Get all schoolmaster
     */
    function get_all_schoolmaster()
    {
        $this->db->order_by('school_id', 'desc');
        return $this->db->get('schoolmaster')->result_array();
    }
        
    /*
     * function to add new schoolmaster
     */
    function add_schoolmaster($params)
    {
        $this->db->insert('schoolmaster',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update schoolmaster
     */
    function update_schoolmaster($school_id,$params)
    {
        $this->db->where('school_id',$school_id);
        return $this->db->update('schoolmaster',$params);
    }
    
    /*
     * function to delete schoolmaster
     */
    function delete_schoolmaster($school_id)
    {
        return $this->db->delete('schoolmaster',array('school_id'=>$school_id));
    }
}
