<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usermaster_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usermaster by userid
     */
    function get_usermaster($userid)
    {
        return $this->db->get_where('usermaster',array('userid'=>$userid))->row_array();
    }
    
    /*
     * Get all usermaster count
     */
    function get_all_usermaster_count()
    {
        $this->db->from('usermaster');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all usermaster
     */
    function get_all_usermaster($params = array())
    {
        $this->db->order_by('userid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('usermaster')->result_array();
    }
        
    /*
     * function to add new usermaster
     */
    function add_usermaster($params)
    {
        $this->db->insert('usermaster',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usermaster
     */
    function update_usermaster($userid,$params)
    {
        $this->db->where('userid',$userid);
        return $this->db->update('usermaster',$params);
    }
    
    /*
     * function to delete usermaster
     */
    function delete_usermaster($userid)
    {
        return $this->db->delete('usermaster',array('userid'=>$userid));
    }
}
